name: ✍️ Document and 🚀 Deployment
on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
  workflow_dispatch:
jobs:
  documents:
    name: "Build and deploy documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Build documentation
        run: |
          python -m pip install --upgrade poetry 
          poetry install
          poetry run mkdocs build

      - name: Deploy PR preview to Surge
        uses: afc163/surge-preview@v1
        id: preview_step
        if: github.event_name == 'pull_request'
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: site
          teardown: 'true'
          build: |
            echo "mkdocs has built site/ already"
      - name: Get the preview_url
        if: github.event_name == 'pull_request'
        run: echo "${{ steps.preview_step.outputs.preview_url }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Deploy to Surge
        if: github.ref == 'refs/heads/main'
        run: |
          npx surge --project site \
                    --domain mycurl.surge.sh \
                    --token ${{ secrets.SURGE_TOKEN }}
